web:
  build: ./api-service
  ports:
    - "5000:5000"
  volumes:
    - .:/todo
  links:
    - db
db:
  image: mongo:3.0.2
  command: --smallfiles
python_script:
  build: .
  command: bash -c "python -u myapp.py"
  volumes:
   - .:/todo
  links:
   - db
